SELECT *
FROM ALL_OBJECTS
WHERE OWNER='HR'
AND OBJECT_TYPE='SYNONYM';


CREATE OR REPLACE PUBLIC SYNONYM DEPARTMENTS
FOR HR.DEPARTMENTS;


CREATE OR REPLACE SYNONYM SYS.LOCATIONS
FOR HR.LOCATIONS;

set SERVEROUTPUT ON
DECLARE
  v_saludo VARCHAR(10):= ' Saludos';
BEGIN
sys.DBMS_OUTPUT.PUT_line(' Yo pongo las chelas '||v_saludo);
END;

DECLARE
  v_fname VARCHAR(300);
BEGIN
  SELECT first_name INTO v_fname FROM employees
  WHERE employee_id = 100;
sys.DBMS_OUTPUT.PUT_line('  '||v_fname);
END;

